#!/usr/bin/env node
/**
 * Regenerates `src/core/protocol/descriptor.generated.ts` from the shared
 * `phk_v1_descriptor.json` produced by PhK-Protocol's `tools/export_descriptor.py`.
 *
 * Usage:
 *   node tools/gen_protocol.mjs [path/to/phk_v1_descriptor.json]
 *
 * The descriptor is the single source of truth for enum numbers and ruleset
 * metadata, so the client never hard-codes them by hand.
 */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
// SpellKard/laya/tools -> ../../.. == the repository parent that holds PhK-Protocol.
const defaultDescriptor = resolve(here, '../../../PhK-Protocol/descriptors/phk_v1_descriptor.json');
const descriptorPath = resolve(process.argv[2] ?? defaultDescriptor);
const outPath = resolve(here, '../src/core/protocol/descriptor.generated.ts');

const descriptor = JSON.parse(readFileSync(descriptorPath, 'utf8'));

const wantedEnums = new Set(['LobbyMessageType', 'BattlePayloadType', 'BusinessOpCode']);
const enums = new Map();
for (const file of descriptor.files ?? []) {
  for (const enumDef of file.enums ?? []) {
    if (wantedEnums.has(enumDef.name)) {
      enums.set(enumDef.name, enumDef.values ?? []);
    }
  }
}

function screamingSnake(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, '$1_$2').toUpperCase();
}

function enumBlock(name, values) {
  const lines = values.map((value) => `  ${value.name}: ${value.number},`);
  return `export const ${name} = {\n${lines.join('\n')}\n} as const;\n\n` +
    `export type ${name}Value = (typeof ${name})[keyof typeof ${name}];\n`;
}

function reverseBlock(name, values) {
  const lines = values.map((value) => `  ${value.number}: '${value.name}',`);
  return `export const ${name}_NAMES: Record<number, string> = {\n${lines.join('\n')}\n};\n`;
}

const parts = [];
parts.push('// AUTO-GENERATED by tools/gen_protocol.mjs — do not edit by hand.');
parts.push(`// Source: PhK-Protocol/${descriptorPath.replace(/\\/g, '/').split('/PhK-Protocol/').pop()}`);
parts.push('/* eslint-disable */\n');

parts.push(`export const DESCRIPTOR_PROTOCOL_VERSION = ${descriptor.protocol_version};`);
parts.push(`export const DESCRIPTOR_BUSINESS_API_VERSION = '${descriptor.business_api_version}';`);
parts.push(`export const DESCRIPTOR_BATTLE_API_VERSION = '${descriptor.battle_api_version}';`);
parts.push(`export const DESCRIPTOR_RULESET_VERSION = '${descriptor.ruleset_version}';`);
parts.push(`export const DESCRIPTOR_RULESET_HASH = '${descriptor.ruleset_hash}';`);
parts.push(`export const DESCRIPTOR_RULESET_REQUIRED_KEYS = ${JSON.stringify(
  descriptor.ruleset_required_keys ?? [],
)} as readonly string[];\n`);

for (const [name, values] of enums) {
  const constName = screamingSnake(name);
  parts.push(enumBlock(constName, values));
  parts.push(reverseBlock(constName, values));
}

mkdirSync(dirname(outPath), { recursive: true });
writeFileSync(outPath, `${parts.join('\n')}\n`, 'utf8');
console.log(`wrote ${outPath}`);
